name: Source Corpus Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_target: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/checkout@v2
        with:
          repository: dvander/sourcepawn-corpus
          submodules: recursive
          path: sourcepawn-corpus

      # Setup Python for AMBuild
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install AMBuild
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild
          pip install progressbar2

      - name: Select clang compiler
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          clang --version
          clang++ --version

      - name: Build
        run: |
          mkdir objdir
          cd objdir
          python ../configure.py --enable-optimize --enable-debug --enable-asan --targets=${{ matrix.build_target }}
          ambuild

      - name: Test
        run: |
          python tools/corpus/run.py objdir/spcomp/linux-x86_64/spcomp ${GITHUB_WORKSPACE}/sourcepawn-corpus -j --fail-fast
